//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RawrzService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public bool can_text { get; set; }
        public bool can_email { get; set; }
        public bool two_factor_authentication { get; set; }
    
        public virtual User User { get; set; }
    }
}
